### PR TITLE
Prevent IE11 caching GET call in Angular 2

### PR DESCRIPTION
**Pull request by reberinformatik**
See also https://github.com/aspnetboilerplate/abp-ng2-module/pull/10
In favor of https://github.com/aspnetboilerplate/bower-abp-resources/pull/4

### CODE REVIEW

**Comment by hikalkan** [comment]
Thank you @reberinformatik for your contribution.

What if options.beforeSend has already set by developer? You are overwriting it. Can you please check it and call previous ``beforeSend`` if possible. Something like:

````js
var oldBeforeSendOption = options.beforeSend;
options.beforeSend = function(xhr) {
    if (oldBeforeSendOption) { 
        oldBeforeSendOption(xhr)
    }

    xhr.setRequestHeader("Pragma", "no-cache");
    xhr.setRequestHeader("Cache-Control", "no-cache");
    xhr.setRequestHeader("Expires", "Sat, 01 Jan 2000 00:00:00 GMT");
};
````

**Comment by reberinformatik** [comment]
Thanks, I just used the code from https://github.com/aspnetboilerplate/bower-abp-resources/pull/4 without thinking. Pull-request updated.

**Comment by hikalkan** [comment]
Thanks a lot.

**Comment by reberinformatik** [comment]
@hikalkan 
Could you do a minor release for this fix? It prevents our site from beeing tested by the gorvenment (they still use IE 11).
Same as:
https://github.com/aspnetboilerplate/abp-ng2-module/issues/12

**Pull request merged**
