### PR TITLE
Update definition type

### PR DESCRIPTION
**Pull request by julianosaless**
Add new parameter  optional domain  to method setCookie

### CODE REVIEW

**Comment by ismcagdas** [comment]
@julianosaless thanks a lot. We forgot to add it when we add domain parameter.

**Comment by julianosaless** [comment]
@ismcagdas  tks  bro, I pleasure  to help this  awesome project!!

**Comment by acjh** [comment]
@ismcagdas Should the milestone be v3.4 instead?

**Comment by ismcagdas** [comment]
@acjh yes, sorry.

**Pull request merged**
